### ISSUE TITLE
Update failure

### ISSUE THREAD

**Issue by jonahshader** [micro-nova/AmpliPiWallPanel#22]
@rickballard reported an issue related to updating in the AmpliPi repo. Moving it here:

Getting "Syntax error on JSON" when attempting to update the Sonoff wall pad from 0.2.0, to either of the latest updates. These errors then offer up a reboot button for the wallpad, because the wallpad is otherwise frozen. It then returns back to its pre-update condition with 0.2.0. Meanwhile, the Amplipi itself is running the latest, and working fine. Any suggestions on how to proceed would be much appreciated. Thanks.

**Comment by jonahshader** [comment]
We were unable to reproduce this behavior so far. We downgraded to 0.2.0 then updated to 0.2.5 with no issues. You could try:

1. Settings -> Advanced -> Factory reset (which just resets the config, like wifi and zone settings)
2. Press the physical reset button with a pin on the bottom of the panel
3. At this point, reconfigure the wifi and try updating to 0.2.5. If that doesn't work, then try downgrading to 0.1.24 then again updating to 0.2.5

**Comment by rickballard** [comment]
The panel became non-responsive, stuck on the error message with the reset button.  The button changed colour when pressed, but the screen would not respond otherwise.  So, I used the reset hole with a pin to press the reset button, and the screen died.  I pulled the screen off the wall, then put it back, but the screen is still dead.  I suspect this panel is defective.  Any suggestions?

**Comment by jonahshader** [comment]
Our support will contact you over email about a replacement. We will continue to diagnose this issue once we get it in our hands.
