### ISSUE TITLE
MQTT stops working after hours on standby

### ISSUE THREAD

**Issue by rwarner** [micro-nova/AmpliPiWallPanel#34]
Over the course of the past week or so (and also on 0.2.9 pre-release) in the morning I'll go to hit the second switch which sends an MQTT over to my broker to turn a light on. When I come back after hours of not touching the device, the MQTT functionality seems to stop working. I'll go to hit the switch off and on and off and nothing happens until I go into

Settings -> Advanced -> MQTT and click "Apply" and then it immediately starts working again

**Comment by jonahshader** [comment]
I tried adding the same "apply" behavior to the auto reconnect function. Could you try the "MQTT Relay Fix" pre-release? It's called relay fix because adding in those changes revealed a different bug where the relay state wasn't being published on apply, but it also contains the changes that should hopefully fix your issue.

Let me know how it goes, thanks!

**Comment by rwarner** [comment]
Hey @jonahshader awesome, installing the 0.2.11 MQTT Relay Fix and will give it a few days and see how it goes and report back. Appreciate the quick turnaround

**Comment by jonahshader** [comment]
I guess it isn't disconnecting then, just getting into some kind of bad state. It's not a great solution but I'll try restarting the MQTT system every few minutes regardless of its connection.

**Comment by jonahshader** [comment]
@rwarner I found a bug that was preventing the auto reconnect from working, so I fixed that instead of what I said above (but there is a good chance that it is still getting into a bad state while still being connected). I also added a loading spinner and a connection icon to the MQTT page. If you have some time, could you try 0.2.12 MQTT Fix 3? If it still doesn't work, let me know if the connectivity icon has a red line through it or not.
Thanks!

**Comment by rwarner** [comment]
Sounds good, I'll install it now and report back after giving it a day or so
